VEHICLE_ID_FORMAT = "pt_{0}"

NETWORK_LANE_CAPACITY=500
NETWORK_ROAD_LANE_COUNT=2
NETWORK_MODE_STR="pt" 
# in meter per second
NETWORK_FREE_SPEED = 6000/3600

TIME_WAITING_MIN = 5
TIME_BETWEEN_STOP_MINUTE = 10

TIME_TRANSIT_START = "08:00:00"
TIME_BETWEEN_NEW_TRANSIT_RELEASE_MINUTE = 5
TIME_TRANSIT_RETURN_MINUTE = 30
#TIME_LARGEST_ROUTE_UNRESTRAINED_COVERING_HOUR = 10

TOTAL_BUS = 300
SEAT = 40
STANDING = 10
LENGTH = 8

TRANSIT_VEHICLE_TYPE_PROP_DICT = \
{
    "pt": {"count": TOTAL_BUS, "seat": SEAT, "standing": STANDING, "length": LENGTH}
}
