VEHICLE_ID_FORMAT = "pb_{0}"

NETWORK_LANE_CAPACITY=50000
NETWORK_ROAD_LANE_COUNT=2
NETWORK_MODE_STR="car,bus"
# in meter per second
NETWORK_FREE_SPEED = 60000/3600

TIME_WAITING_MIN = 2
TIME_BETWEEN_STOP_MINUTE = 5

TRANSIT_MODE="bus"
TIME_TRANSIT_START = "08:00:00"
TIME_BETWEEN_NEW_TRANSIT_RELEASE_MINUTE = 30
TRANSIT_RUN_TIME_HOUR_LENGTH = "12:00:00"
#TIME_TRANSIT_RETURN_MINUTE = 120
#TIME_LARGEST_ROUTE_UNRESTRAINED_COVERING_HOUR = 10

TOTAL_BUS = 1500
SEAT = 40
STANDING = 10
LENGTH = 8

TRANSIT_VEHICLE_TYPE_PROP_DICT = \
{
    "pb": {"id": "pb", "count": TOTAL_BUS, "seat": SEAT, "standing": STANDING, "length": LENGTH, "pce": (SEAT+STANDING)/4}
}
